/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/answer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["answer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/question": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_question"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["start_game"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        Answer: "yes" | "no" | "unsure";
        AnswerQuestionBody: {
            answer: components["schemas"]["Answer"];
        };
        GameApiResponse: {
            question: string;
            /** @enum {string} */
            type: "new_question";
        } | {
            /** @enum {string} */
            type: "no_questions_left";
        } | {
            name: string;
            scientific_name: string;
            /** @enum {string} */
            type: "animal_guess";
        };
        /** @enum {string} */
        GameMode: "classic" | "expert";
        StartGameBody: {
            game_mode: components["schemas"]["GameMode"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    answer: {
        parameters: {
            query?: {
                lang?: string | null;
            };
            header?: never;
            path?: never;
            cookie: {
                /** @description Session ID defining your session */
                sid: string;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnswerQuestionBody"];
            };
        };
        responses: {
            /** @description Answered successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameApiResponse"];
                };
            };
            /** @description Server failure */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_question: {
        parameters: {
            query?: {
                lang?: string | null;
            };
            header?: never;
            path?: never;
            cookie: {
                /** @description Session ID defining your session */
                sid: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Received a question */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameApiResponse"];
                };
            };
            /** @description Server failure */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    start_game: {
        parameters: {
            query?: {
                lang?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: {
                /** @description Session ID defining your session */
                sid?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartGameBody"];
            };
        };
        responses: {
            /** @description Game started successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameApiResponse"];
                };
            };
            /** @description Server failure */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
