/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/answer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["answer_question"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/question": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_question"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["start_game"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AnimalDto: {
            scientific_name: string;
            token: components["schemas"]["I18nToken"];
        };
        /** @enum {string} */
        Answer: "yes" | "no" | "unsure";
        AnswerQuestionBody: {
            answer: components["schemas"]["Answer"];
        };
        AnswerQuestionResponse: {
            /** @enum {string} */
            type: "answered";
        } | {
            animal: components["schemas"]["AnimalDto"];
            /** @enum {string} */
            type: "animal_guess";
        };
        GameDto: {
            animal: null | components["schemas"]["AnimalDto"];
            question: null | components["schemas"]["QuestionDto"];
            question_history: components["schemas"]["QuestionHistoryEntryDto"][];
            /** Format: int32 */
            round: number;
            state: components["schemas"]["GameStateDto"];
        };
        /** @enum {string} */
        GameMode: "classic" | "expert";
        GameStateDto: {
            /** @enum {string} */
            type: "in_progress";
        } | {
            /** @enum {string} */
            type: "failed";
        } | {
            /** @enum {string} */
            type: "finished";
        };
        GetQuestionResponse: {
            question: components["schemas"]["QuestionDto"];
            /** @enum {string} */
            type: "new_question";
        } | {
            /** @enum {string} */
            type: "no_questions_left";
        };
        I18nToken: {
            key: string;
            ns: string | null;
            values: unknown;
        };
        QuestionDto: {
            token: components["schemas"]["I18nToken"];
        };
        QuestionHistoryEntryDto: {
            answer: components["schemas"]["Answer"];
            question: components["schemas"]["QuestionDto"];
        };
        /** @description --------------- Input Body --------------- */
        StartGameBody: {
            force: boolean;
            game_mode: components["schemas"]["GameMode"];
        };
        /** @description --------------- Responses --------------- */
        StartGameResponse: {
            /** @enum {string} */
            type: "new_game_started";
        } | {
            game: components["schemas"]["GameDto"];
            /** @enum {string} */
            type: "game_already_exists";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    answer_question: {
        parameters: {
            query?: {
                lang?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnswerQuestionBody"];
            };
        };
        responses: {
            /** @description Answered successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnswerQuestionResponse"];
                };
            };
            /** @description No active game or no question to answer */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Server failure */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_question: {
        parameters: {
            query?: {
                lang?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Received a question */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetQuestionResponse"];
                };
            };
            /** @description No active game */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Server failure */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    start_game: {
        parameters: {
            query?: {
                lang?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartGameBody"];
            };
        };
        responses: {
            /** @description Game started successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StartGameResponse"];
                };
            };
            /** @description Game already running */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Server failure */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
